### PR TITLE
Adding the ability to use empty values

### PR DESCRIPTION
**Pull request by vityevato**
Fixes #

### Proposed changes
Some proprietary servers may return an authorization header with empty field values. 

For example:
ISAPI implementation for **hikvision DS-KV6113-PE1(C)** (firmware: V2.2.65 build 230703) in the authorization header it says

`WWW-Authenticate: Digest qop="auth", realm="DS-DD8D92DB", nonce="NzhiYWNkMGY3ZmVjZGZkNjA1NzE0NzcxYzA4MTBmNjM=", stale="false", opaque="", domain="::"`

As we can see, there is `opaque=""` , which is initially incorrectly processed by the library's conversion functions.

Since this library is used in the [Scrypted](https://github.com/koush/scrypted) project, this entails the lack of normal connection to the camera **hikvision DS-KV6113-PE1(C)**

I propose to these PR to process empty key values. In the new tests you can see how to process them :)

### Code quality
- [X] I made some tests for my changes
- [X] I added my name in the
 [contributors](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
 field of the `package.json` file. Beware to use the same format than for the author field
 for the entries so that you'll get a mention in the `README.md` with a link to your website.

### License
To get your contribution merged, you must check the following.

- [X] I read the project license in the LICENSE file
- [X] I agree with publishing under this project license

### Join
- [ ] I wish to join the core team
- [ ] I agree that with great powers comes responsibilities
- [ ] I'm a nice person

My NPM username:
I don't have :)

### CODE REVIEW

**Review by nfroidure — CHANGES_REQUESTED** [review]
Thank you for your explanation and PR. It is almost ok to merge it, please just remove the version in the `package.json` file since I will create the version myself in a separate commit and everything that goes with it (CHANGELOG). Also, I think I will do a major version sin the change may break some codebase.

**Comment by nfroidure** [comment]
@Stillness-2 can you squash it into one commit please and validate it with the conventional commit format (see other commits of the project)? Using `npm run cz` to commit will guide you.

**Review by nfroidure — COMMENTED** [review]
@Stillness-2 can you squash it into one commit please and validate it with the conventional commit format (see other commits of the project)? Using npm run cz to commit will guide you.

**Comment by vityevato** [comment]
I'll try to do it a little later :)

**Review by nfroidure — APPROVED** [review]
LGTM

**Comment by nfroidure** [comment]
@Stillness-2 thanks for contributing, just published the v6.0.0

**Pull request merged**
